[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
option_create = "9SaKv891pjh3YMtvUxL5jHQc77Gs6Ay4uy2PifX5AEPL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
